### ISSUE TITLE
2.2.4 Modelos relacionales de datos

### ISSUE THREAD

**Issue by AlexisBs** [tectijuana/conocimiento#4]
 2.2.5 Ontologías
 2.3 Formalización del conocimiento
 2.4 Construcción y razonamiento

**Comment by IoTeacher** [comment]
# OLAP 
![](https://images.cooltext.com/5390740.png)

<a href="http://es.cooltext.com" target="_top"><img src="https://cooltext.com/images/ct_pixel.gif" width="80" height="15" alt="Cool Text: Generador de Logotipos y Gráficos." border="0" /></a>

**Comment by AlexisBs** [comment]
**<h1>2.2.4 Modelos relacionales de datos </h1>**
<hr>
<p align="justify">El modelo relacional para la gestión de una base de datos es un modelo de datos basado en la lógica de predicados y en la teoría de conjuntos. Es el modelo más utilizado en la actualidad para modelar problemas reales y administrar datos dinámicamente. </p>
<p align="center"><img src="https://sites.google.com/site/fbdluissantiago15210344t/_/rsrc/1453347953391/bibliografia/4-diseno-de-base-de-datos-relacionales/4.gif" style="max-width:100%;"></p>
<p align="justify">En este modelo todos los datos son almacenados en relaciones, y como cada relación es un conjunto de datos, el orden en el que éstos se almacenen no tiene relevancia (a diferencia de otros modelos como el jerárquico y el de red).  </p>
<p align="center"><img src="https://lh3.googleusercontent.com/proxy/x5xqVilwXZR8Ju6YEosDaBTDbVN9e2VXWs_lyiVeM-BLVV1PCKG2Gu9MdnYh0TBg6wpAfccSpX2tE8B02yyMjv8" style="max-width:100%;"></p>

<p align="justify"> Esto tiene la considerable ventaja de que es más fácil de entender y de utilizar por un usuario no experto. La información puede ser recuperada o almacenada por medio de consultas que ofrecen una amplia flexibilidad y poder para administrar la información.</p>
<p align="center"><img src="https://sites.google.com/site/nicoticsuce/_/rsrc/1454458321063/unidad-1/13-modelos-relacionales-de-base-de-datos/4.gif" style="max-width:100%;"></p>

<p align="justify">Este modelo considera la base de datos como una colección de relaciones. De manera simple, una relación representa una tabla que no es más que un conjunto de filas, cada fila es un conjunto de campos y cada campo representa un valor que interpretado describe el mundo real </p>
<p align="center"><img src="https://1.bp.blogspot.com/_6ddsurxKnIQ/TGR8Wl6cA2I/AAAAAAAAAAU/y_WXKg7Ckk0/s1600/4350.GIF" style="max-width:100%;"></p>

**<h1>  2.2.5 Ontologías</h1>**
<hr>
<p  align="justify"> Término ontología la identifica con "la rama de la metafísica que estudia la naturaleza de la existencia". En las aplicaciones reales, sin embargo, una ontología es una entidad computacional, y no ha de ser considerada como una entidad natural que se descubre, sino como recurso artificial que se crea. </p>
<p align="center"><img src="https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2019/08/inteligencia-artificial.jpg" style="max-width:100%;"></p>
**<h2> TIPOS DE ANTOLOGÍAS </h2>**

- Ontologías de un dominio: en las que se representa el conocimiento especializado pertinente de un dominio o subdominio, como la medicina, las aplicaciones militares, la cardiología o, en nuestro caso particular, la oncología.
- Ontologías genéricas: en las que se representan conceptos generales y fundacionales del conocimiento como las estructuras parte/todo, la cuantificación, los procesos o los tipos de objetos.
- Ontologías representacionales: en las que se especifican las conceptualizaciones que subyacen a los formalismos de representación del conocimiento, por lo que también se denominan meta-ontologías (meta-level o top-level ontologies).

**<h1> 2.3 Formalización del conocimiento</h1>**
<hr>
<p align="justify"> Un ideal en todo tipo de conocimientos, independientemente de la certeza, verdad o utilidad de sus conclusiones, es la claridad, simpleza y economía en su expresión. Esto puede lograrse reduciendo tanto como sea posible los términos primitivos de la teoría de modo tal que los demás conceptos del cuerpo de conocimientos puedan definirse a partir de una reducida suma de conceptos postulados como ciertos.</p>
<p align="center"><img src="https://www.secureweek.com/wp-content/uploads/2019/11/La-Inteligencia-Artificial-aun-no-est%C3%A1-cera-de-la-Inteligencia-Real.jpg" style="max-width:100%;"></p>


<p align="justify">En ese sistema sobre la base de unas pocas afirmaciones ciertas e intuitivamente evidentes, se asienta una explicación satisfactoria el resto de conceptos de la geometría plana. 
</p>
<p align="justify">Esto es asimismo lo propugnado por Aristóteles, para quien, anota Torretti (1998, p71), “todo conocimiento científico propiamente tal se establece por inferencia deductiva a partir de principios de dos clases, a saber, conceptos que no se definen y aseveraciones que no se demuestran”.  </p>


https://tec.mx/sites/default/files/styles/header_full/public/2018-10/MICAI%20portada.png?h=dc99fa49&itok=041m0Ygn

**<h1>  2.4 Construcción y razonamiento </h1>**

<p align="justify"> Los conocimientos lógicos y matemáticos, gracias a su formalización, se expresan mediante fórmulas. En rigor constituyen lenguajes. El método axiomático no ha logrado desarrollo satisfactorio en la formalización del conocimiento empírico, y tampoco en la formalización del conocimiento jurídico. La dificultad radica en que no se ha encontrado una regla o método de aceptación general que sirva para definir rigurosamente las relaciones entre los términos del lenguaje con que se expresan los conocimientos empíricos y los hechos de la realidad.  </p>
<p align="justify">En cierto modo es correcto afirmar que los aviones vuelan y los puentes se sostienen porque los cálculos son correctos, pero también que si alguna vez se caen a despecho de la corrección de los cálculos, seguramente es porque no hay identidad entre los términos del lenguaje y los hechos del mundo (o no está a nuestro alcance asirla).   </p>
